import re
from datetime import datetime

# Activity.time_slot is free text generated by Claude (e.g. "09:00 - 11:00")
# with no schema/DB format enforcement — only an example in the system
# prompt. This matches on raw HH:MM substrings rather than a strict
# full-string pattern, so it tolerates surrounding text ("Afternoon
# (14:00 - 17:00)"), different separators, and missing spaces.
_TIME_RE = re.compile(r'(\d{1,2}):(\d{2})')


def parse_time_slot(time_slot: str) -> tuple[int, int] | None:
    """Extract an inclusive (start_hour, end_hour) window, both 0-23, from a
    free-text time_slot. Returns None if it can't be confidently parsed —
    callers must treat None as "no reliable window", not as a degenerate
    (0, 23) range, and fall back to their own safe default.

    A single matched time (no range) is treated as a 1-hour window at that
    hour. End-before-start ranges (e.g. "22:00 - 01:00") are treated as
    unparseable rather than handled as overnight wraparound — real activity
    time slots essentially never span midnight, and the hourly data this
    feeds from is already sliced to one calendar day.
    """
    matches = _TIME_RE.findall(time_slot or "")
    if not matches:
        return None

    def _hour(pair):
        h = int(pair[0])
        return h if 0 <= h <= 23 else None

    if len(matches) == 1:
        h = _hour(matches[0])
        return (h, h) if h is not None else None

    start, end = _hour(matches[0]), _hour(matches[1])
    if start is None or end is None or end < start:
        return None
    return (start, end)


def hourly_window_is_rainy(hourly_day: list[dict], window: tuple[int, int], threshold: float) -> bool:
    """True if any hourly entry within `window` (inclusive start/end hour)
    has a rain_probability at or above `threshold`. `hourly_day` should
    already be filtered to the one calendar day `window` applies to."""
    start_hour, end_hour = window
    for entry in hourly_day:
        hour = datetime.fromisoformat(entry["time"]).hour
        if start_hour <= hour <= end_hour and (entry.get("rain_probability") or 0) >= threshold:
            return True
    return False
