import re
from datetime import datetime

# Activity.time_slot is free text generated by Claude (e.g. "09:00 - 11:00")
# with no schema/DB format enforcement — only an example in the system
# prompt. This matches on raw HH:MM substrings rather than a strict
# full-string pattern, so it tolerates surrounding text ("Afternoon
# (14:00 - 17:00)"), different separators, and missing spaces.
_TIME_RE = re.compile(r'(\d{1,2}):(\d{2})')


def parse_time_slot(time_slot: str) -> tuple[int, int] | None:
    """Extract an inclusive (start_hour, end_hour) window, both 0-23, from a
    free-text time_slot. Returns None if it can't be confidently parsed —
    callers must treat None as "no reliable window", not as a degenerate
    (0, 23) range, and fall back to their own safe default.

    A single matched time (no range) is treated as a 1-hour window at that
    hour. End-before-start ranges (e.g. "22:00 - 01:00") are treated as
    unparseable rather than handled as overnight wraparound — real activity
    time slots essentially never span midnight, and the hourly data this
    feeds from is already sliced to one calendar day.
    """
    matches = _TIME_RE.findall(time_slot or "")
    if not matches:
        return None

    def _hour(pair):
        h = int(pair[0])
        return h if 0 <= h <= 23 else None

    if len(matches) == 1:
        h = _hour(matches[0])
        return (h, h) if h is not None else None

    start, end = _hour(matches[0]), _hour(matches[1])
    if start is None or end is None or end < start:
        return None
    return (start, end)


def hourly_window_is_rainy(hourly_day: list[dict], window: tuple[int, int], threshold: float) -> bool:
    """True if any hourly entry within `window` (inclusive start/end hour)
    has a rain_probability at or above `threshold`. `hourly_day` should
    already be filtered to the one calendar day `window` applies to."""
    start_hour, end_hour = window
    for entry in hourly_day:
        hour = datetime.fromisoformat(entry["time"]).hour
        if start_hour <= hour <= end_hour and (entry.get("rain_probability") or 0) >= threshold:
            return True
    return False


def _hourly_window_values(hourly_day: list[dict], window: tuple[int, int], field: str) -> list[float]:
    """Every non-None value of `field` among hourly entries within `window`
    (inclusive start/end hour) — shared by the hourly_window_min_*/max_*
    helpers below, which just reduce this list differently depending on
    which direction is "worst" for that metric."""
    start_hour, end_hour = window
    return [
        entry[field]
        for entry in hourly_day
        if start_hour <= datetime.fromisoformat(entry["time"]).hour <= end_hour
        and entry.get(field) is not None
    ]


def hourly_window_min_visibility_km(hourly_day: list[dict], window: tuple[int, int]) -> float | None:
    """Worst (lowest) visibility_km among hourly entries within `window`, or
    None if no entry falls in that window (or none of them carry a
    visibility_km at all — e.g. hourly fixtures built for rain-only
    testing). Same refinement idea as hourly_window_is_rainy above, applied
    to fog scoring instead of rain — the activity's own time slot might miss
    a fog bank that only affects a different part of the day."""
    values = _hourly_window_values(hourly_day, window, "visibility_km")
    return min(values) if values else None


def hourly_window_max_wind_speed(hourly_day: list[dict], window: tuple[int, int]) -> float | None:
    """Worst (highest) wind_speed within `window` — same refinement idea as
    hourly_window_min_visibility_km above, applied to wind instead."""
    values = _hourly_window_values(hourly_day, window, "wind_speed")
    return max(values) if values else None


def hourly_window_max_uv_index(hourly_day: list[dict], window: tuple[int, int]) -> float | None:
    """Worst (highest) uv_index within `window`."""
    values = _hourly_window_values(hourly_day, window, "uv_index")
    return max(values) if values else None


def hourly_window_min_temperature(hourly_day: list[dict], window: tuple[int, int]) -> float | None:
    """Worst (coldest) temperature within `window` — feeds cold-risk
    scoring, mirroring the day-level temp_min this refines."""
    values = _hourly_window_values(hourly_day, window, "temperature")
    return min(values) if values else None


def hourly_window_max_temperature(hourly_day: list[dict], window: tuple[int, int]) -> float | None:
    """Worst (hottest) temperature within `window` — feeds heat-risk
    scoring, mirroring the day-level temp_max this refines."""
    values = _hourly_window_values(hourly_day, window, "temperature")
    return max(values) if values else None
