import pytest
from services.flights_service import search_flights

# These tests now work with the dynamic data generated by your CSV
def test_flight_search_returns_flights(auth_client):
    # Searching for a route that exists in your generated CSV
    response = auth_client.get("/api/flights/search?origin=London,%20UK&departure=2026-07-16&return_date=2026-07-23&destination=Paris,%20France&direction=arrival")
    assert response.status_code == 200
    data = response.json()
    assert "flights" in data
    assert isinstance(data["flights"], list)
    if len(data["flights"]) > 0:
        assert data["flights"][0]["departure_city"] == "London, UK"
        assert data["flights"][0]["destination_city"] == "Paris, France"

def test_flight_search_departure_direction_reframes_as_leaving_london(auth_client):
    # Testing the return leg: Paris -> London
    response = auth_client.get(
        "/api/flights/search?origin=London,%20UK&departure=2026-07-16&return_date=2026-07-23&destination=Paris,%20France&direction=departure"
    )
    assert response.status_code == 200
    flights = response.json()["flights"]
    if len(flights) > 0:
        assert flights[0]["departure_city"] == "Paris, France"
        assert flights[0]["destination_city"] == "London, UK"

def test_flight_search_filters_by_flight_number_when_given(auth_client):
    # Step 1: Get a real flight number from the CSV
    search_res = auth_client.get("/api/flights/search?origin=London,%20UK&departure=2026-07-16&return_date=2026-07-23&destination=Paris,%20France&direction=arrival")
    flights = search_res.json()["flights"]

    if len(flights) > 0:
        valid_f_num = flights[0]["flight_number"]

        # Step 2: Test filtering
        response = auth_client.get(
            f"/api/flights/search?origin=London,%20UK&departure=2026-07-16&return_date=2026-07-23&destination=Paris,%20France&direction=arrival&flight_number={valid_f_num}"
        )
        assert response.status_code == 200
        filtered = response.json()["flights"]
        assert len(filtered) > 0
        assert all(f["flight_number"] == valid_f_num for f in filtered)

def test_flight_search_no_results_empty_list(auth_client):
    # Searching for a non-existent route should return an empty list, not an error
    response = auth_client.get("/api/flights/search?origin=London,%20UK&departure=2026-07-16&return_date=2026-07-23&destination=Moon,%20Space&direction=arrival")
    assert response.status_code == 200
    assert response.json()["flights"] == []