"""add flight info to trips

Revision ID: 22ae406a1452
Revises: fd6c3ec118a6
Create Date: 2026-07-06 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22ae406a1452'
down_revision: Union[str, Sequence[str], None] = 'fd6c3ec118a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('arrival_flight_number', sa.String(length=20), server_default='', nullable=False))
    op.add_column('trips', sa.Column('arrival_airline', sa.String(length=100), server_default='', nullable=False))
    op.add_column('trips', sa.Column('arrival_time', sa.String(length=10), server_default='', nullable=False))
    op.add_column('trips', sa.Column('departure_flight_number', sa.String(length=20), server_default='', nullable=False))
    op.add_column('trips', sa.Column('departure_airline', sa.String(length=100), server_default='', nullable=False))
    op.add_column('trips', sa.Column('departure_time', sa.String(length=10), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'departure_time')
    op.drop_column('trips', 'departure_airline')
    op.drop_column('trips', 'departure_flight_number')
    op.drop_column('trips', 'arrival_time')
    op.drop_column('trips', 'arrival_airline')
    op.drop_column('trips', 'arrival_flight_number')
    # ### end Alembic commands ###
