"""add lat lng to trips

Revision ID: 41fee3f3ac8c
Revises: bca36bc549b0
Create Date: 2026-07-22 11:18:27.036894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41fee3f3ac8c'
down_revision: Union[str, Sequence[str], None] = 'bca36bc549b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('lat', sa.Float(), server_default='0', nullable=False))
    op.add_column('trips', sa.Column('lng', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'lng')
    op.drop_column('trips', 'lat')
    # ### end Alembic commands ###
