"""add_revert_tracking_to_activities

Revision ID: 5f89fbd41ecf
Revises: 8d23b68fd8e8
Create Date: 2026-08-11 10:27:53.720013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f89fbd41ecf'
down_revision: Union[str, Sequence[str], None] = '8d23b68fd8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('swapped_at', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('reverted_at', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('is_reverted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('activities', sa.Column('revert_reason', sa.String(length=255), server_default='', nullable=False))
    op.add_column('activities', sa.Column('revert_score', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'revert_score')
    op.drop_column('activities', 'revert_reason')
    op.drop_column('activities', 'is_reverted')
    op.drop_column('activities', 'reverted_at')
    op.drop_column('activities', 'swapped_at')
    # ### end Alembic commands ###
