"""add other_time fields to trips flights

Revision ID: a9b0ed806487
Revises: 7d44515b8bfd
Create Date: 2026-07-08 09:32:00.183035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b0ed806487'
down_revision: Union[str, Sequence[str], None] = '7d44515b8bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('arrival_other_time', sa.String(length=10), server_default='', nullable=False))
    op.add_column('trips', sa.Column('departure_other_time', sa.String(length=10), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'departure_other_time')
    op.drop_column('trips', 'arrival_other_time')
    # ### end Alembic commands ###
