"""add lat lng to activities

Revision ID: bca36bc549b0
Revises: a9b0ed806487
Create Date: 2026-07-08 18:46:15.050275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca36bc549b0'
down_revision: Union[str, Sequence[str], None] = 'a9b0ed806487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('lat', sa.Float(), server_default='0', nullable=False))
    op.add_column('activities', sa.Column('lng', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'lng')
    op.drop_column('activities', 'lat')
    # ### end Alembic commands ###
