"""add swap fields to activities

Revision ID: fd6c3ec118a6
Revises: 8fb84d40a4b1
Create Date: 2026-06-23 20:21:33.059111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6c3ec118a6'
down_revision: Union[str, Sequence[str], None] = '8fb84d40a4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('alternate_name', sa.String(length=255), server_default='', nullable=False))
    op.add_column('activities', sa.Column('alternate_location', sa.String(length=255), server_default='', nullable=False))
    op.add_column('activities', sa.Column('swap_reason', sa.String(length=255), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'swap_reason')
    op.drop_column('activities', 'alternate_location')
    op.drop_column('activities', 'alternate_name')
    # ### end Alembic commands ###
